from . import school_config
from . import school_class
from . import school_student
from . import school_teacher
from . import school_timetable
from . import school_attendance
from . import school_fees
from . import school_exam
from . import school_homework
from . import school_library
from . import school_transport
from . import school_hostel
from . import school_communication
from . import school_dashboard
